// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 通用应用服务:版本、端口、健康、退出。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetServerPort 返回本地 api-server 监听端口,前端用来拼 BASE_URL。
 * Web 端模式下(无 local server)返回 0,前端应忽略该值走相对路径。
 * @returns {$CancellablePromise<number>}
 */
export function GetServerPort() {
    return $Call.ByID(3953666928);
}

/**
 * GetVersion 返回应用版本号。
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1993855816);
}

/**
 * Health 返回本地 server 健康状态;Web 端返回 "web" 表示非桌面部署。
 * @returns {$CancellablePromise<string>}
 */
export function Health() {
    return $Call.ByID(4150998110);
}

/**
 * Quit 优雅退出应用(由前端触发,如用户主动退出按钮)。
 * 这里通过 Wails 主循环退出,后端 server 由 main 协程的 Serve 阻塞、
 * 进程退出时被 OS 强制关闭。
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(4143596183);
}
