// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AppService from "./appservice.js";
import * as NotifyService from "./notifyservice.js";
import * as PlatformService from "./platformservice.js";
import * as PrefsService from "./prefsservice.js";
import * as ShortcutService from "./shortcutservice.js";
import * as WindowService from "./windowservice.js";
export {
    AppService,
    NotifyService,
    PlatformService,
    PrefsService,
    ShortcutService,
    WindowService
};
