// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotifyService 暴露给前端的通知服务。
 * 仅做"通知层"的事,业务逻辑不允许塞到这里。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * HasPermission 查询当前通知授权状态。
 * @returns {$CancellablePromise<boolean>}
 */
export function HasPermission() {
    return $Call.ByID(1033469893);
}

/**
 * RequestAuthorization 触发系统弹授权窗(macOS 首次启动会弹系统对话框)。
 * 返回 true = 用户允许,false = 拒绝或失败。
 * @returns {$CancellablePromise<boolean>}
 */
export function RequestAuthorization() {
    return $Call.ByID(2221404800);
}

/**
 * Show 发送一条系统通知。
 * id 留空时由 Notifier 内部生成;title 必填;body 可选。
 * @param {string} id
 * @param {string} title
 * @param {string} body
 * @returns {$CancellablePromise<void>}
 */
export function Show(id, title, body) {
    return $Call.ByID(11870127, id, title, body);
}
