// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlatformService 暴露平台/系统能力给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Arch 返回架构,如 "arm64" / "amd64"。
 * @returns {$CancellablePromise<string>}
 */
export function Arch() {
    return $Call.ByID(2823587296);
}

/**
 * ClipboardText 读取剪贴板文本。
 * @returns {$CancellablePromise<string>}
 */
export function ClipboardText() {
    return $Call.ByID(2614262549);
}

/**
 * OS 返回 "darwin" / "windows" / "linux" 等。
 * @returns {$CancellablePromise<string>}
 */
export function OS() {
    return $Call.ByID(1302964098);
}

/**
 * OpenExternal 用系统默认浏览器打开 URL。
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenExternal(url) {
    return $Call.ByID(101294999, url);
}

/**
 * SetClipboardText 写入剪贴板文本。
 * @param {string} text
 * @returns {$CancellablePromise<boolean>}
 */
export function SetClipboardText(text) {
    return $Call.ByID(1614291029, text);
}
