// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PrefsService 暴露给前端的桌面端偏好服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Get 取单个偏好值;不存在返回 ("", false, nil)。
 * @param {string} key
 * @returns {$CancellablePromise<[string, boolean]>}
 */
export function Get(key) {
    return $Call.ByID(79234071, key);
}

/**
 * GetAll 返回所有偏好的快照。
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetAll() {
    return $Call.ByID(1555090834).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Set 写入单个偏好。
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function Set(key, value) {
    return $Call.ByID(1993461955, key, value);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
