// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShortcutService 暴露给前端的全局快捷键服务。
 * 业务侧只关心 combo 字符串,具体平台实现(macOS Carbon / Windows RegisterHotKey)
 * 由 desktop.ShortcutManager 内部消化。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * List 返回当前已注册的所有 combo。
 * @returns {$CancellablePromise<string[]>}
 */
export function List() {
    return $Call.ByID(668860569).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Register 注册一个全局快捷键;成功返回 true。
 * 失败原因(平台不支持 / 缺权限 / combo 不合法)由 mgr.Register 的 error 描述。
 * @param {string} combo
 * @returns {$CancellablePromise<boolean>}
 */
export function Register(combo) {
    return $Call.ByID(662812840, combo);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
