// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 暴露给前端的窗口控制能力。
 * 仅做"窗口层"的事,业务逻辑不允许塞到这里。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Show 主窗口。
 * @returns {$CancellablePromise<void>}
 */
export function Show() {
    return $Call.ByID(245278382);
}

/**
 * ToggleAlwaysOnTop 切换窗口置顶,返回切换后的状态。
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleAlwaysOnTop() {
    return $Call.ByID(1110897318);
}

/**
 * ToggleMaximise 切换窗口最大化。
 * @returns {$CancellablePromise<void>}
 */
export function ToggleMaximise() {
    return $Call.ByID(712406656);
}
