db:
    mysql:
        db: ""
        ip: 127.0.0.1
        port: "3306"
        pwd: "123456"
        user: root
    pgsql:
        db: ""
        ip: 127.0.0.1
        port: "5432"
        pwd: "123456"
        user: root
    sqlite:
        db_path: data.db
    use_type: sqlite
email:
    client:
        account: dicoder@126.com
        host: smtp.126.com
        port: "465"
        pwd: "12345"
server:
    port: "8082"
skillbox:
    auto_backup: "true"
    default_scope: global
    preset_skills_dir: ""
    store_root: ""
    tool_paths: ""
system:
    app_name: dianji
    need_auth: "true"
    user_center_url: http://localhost:8082
tencent:
    cos:
        allow_prefix: ""
        bucket_app_id: ""
        bucket_name: ""
        duration: "0"
        region: ""
        secret_id: ""
        secret_key: ""
